# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160813_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=30)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='amount',
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_from',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_to',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_from',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_to',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='currency_from',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='currency_to',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='exchange',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Transaction'),
        ),
    ]
