# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160819_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
