# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-13 16:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='commissions',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0E-8'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount_from',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount_to',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='exchange',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
    ]
