# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-13 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160913_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='parent',
        ),
    ]
