# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_transfer_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='merchant_reference',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='exchange',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
