# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-15 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160913_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
