# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-23 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160915_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='merchant_reference',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
